# Generated by Django 3.2.4 on 2021-06-27 22:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor_post',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ManuChaoTM', 'ManuChaoTM'), ('HenriqueG', 'HenriqueG')], default='Escolha autor', max_length=20),
        ),
    ]
