# Generated by Django 3.2.4 on 2021-06-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0002_post_autor_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor_post',
            field=models.CharField(choices=[('ManuChaoTM', 'ManuChaoTM'), ('HenriqueG', 'HenriqueG')], default='Escolha autor', max_length=20),
        ),
    ]
