# Generated by Django 3.2.4 on 2021-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0003_alter_post_autor_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_post',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='autor_post',
            field=models.CharField(choices=[('ManuChaoTM', 'ManuChaoTM'), ('HenriqueG', 'HenriqueG')], max_length=20),
        ),
    ]
