# Generated by Django 3.2.4 on 2021-06-27 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0004_auto_20210627_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateField(default=datetime.date(2021, 6, 27)),
        ),
    ]
