# Generated by Django 3.2.4 on 2021-06-27 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0005_alter_post_data_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateField(default=datetime.datetime(2021, 6, 27, 22, 25, 23, 951306, tzinfo=utc)),
        ),
    ]
