# Generated by Django 3.2.4 on 2021-06-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0009_auto_20210627_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_poste',
        ),
    ]
