# Generated by Django 3.2.4 on 2021-07-04 22:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0011_post_data_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='texto_poste',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
