# Generated by Django 3.2.4 on 2021-07-04 22:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0012_post_texto_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto_poste',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
