# Generated by Django 3.2.4 on 2021-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0014_alter_post_autor_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['titulo']},
        ),
        migrations.AddField(
            model_name='post',
            name='img_poste',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
