# Generated by Django 3.2.4 on 2021-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0015_auto_20210705_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_poste',
        ),
        migrations.AddField(
            model_name='post',
            name='imgens_poste',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
