# Generated by Django 3.2.4 on 2021-07-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BanalCast', '0016_auto_20210705_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgens_poste',
            new_name='imagens_poste',
        ),
    ]
